### ISSUE TITLE
Updated Deku's sound tutorial

### ISSUE THREAD

**Issue by Axce** [gbadev-org/awesome-gbadev#56]
Hello!

Wouldn't it be better to replace [Deku's sound tutorial](https://deku.gbadev.org/program/sound1.html) by this updated version ? https://stuij.github.io/deku-sound-tutorial/

It's actually the one used in gbadev's tonc : https://gbadev.net/tonc/sndsqr.html

Thank you!

**Comment by exelotl** [comment]
Yes, agreed! Feel free to make a PR (or I'll get to it later in the week) :)

**Comment by avivace** [comment]
I'm on this

**Comment by Axce** [comment]
Perfect, thank you!
